
server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: CONSUMER

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  cache: false